name: Deploy main branch to Amazon Lambda Serverless
'on':
  push:
    branches:
      - main
env:
  AWS_REGION: ap-southeast-2
jobs:
  build-deploy-dotnet-serverless-api:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup dotnet runtime sdk
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build project
        run: dotnet build --no-restore
      - name: Test project
        run: dotnet test --no-build --verbosity normal
      - name: Setup SAM (Serverless Application Model)
        uses: aws-actions/setup-sam@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: '${{ secrets.AWS_ACCESS_KEY_ID }}'
          aws-secret-access-key: '${{ secrets.AWS_SECRET_ACCESS_KEY }}'
          aws-region: '${{ env.AWS_REGION }}'
      - run: sam build --use-container --mount-with WRITE
      - run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset
          --stack-name aws-sam-dotnet-serverless-api-with-dynamodb --s3-bucket vstiara-deployment-content
          --capabilities CAPABILITY_IAM --region ${{ env.AWS_REGION }}